# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: 首页
    url: '/home'
    weight: 10
  - name: Products
    pageRef: /products
    weight: 20
  - name: Services
    pageRef: /services
    weight: 30
  - name: 内容
    url: '/post'
    weight: 40
  - name: 归档
    url: '/archive'
    weight: 50
  - name: Publications
    url: '#featured'
    weight: 60
  - name: 订阅
    url: '/subscribe'
    weight: 70
  - name: 关于
    url: 'about/admin'
    weight: 800

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
