############################
## HUGO MODULES
## Install or uninstall themes and plugins here.
## Docs: https://gohugo.io/hugo-modules/
############################

imports:
  - path: ./theme-academic-cv/blox-plugin-netlify
  - path: ./theme-academic-cv/blox-plugin-reveal
  - path: ./theme-academic-cv/blox-bootstrap/v5
